#ifndef VGA_COLORS_H
#define VGA_COLORS_H

typedef enum vga_color_t {
    VGA_COLOR_BLACK = 0x00,
    VGA_COLOR_BLUE = 0x01,
    VGA_COLOR_GREEN = 0x02,
    VGA_COLOR_CYAN = 0x03,
    VGA_COLOR_RED = 0x04,
    VGA_COLOR_MAGENTA = 0x05,
    VGA_COLOR_BROWN = 0x06,
    VGA_COLOR_LIGHT_GREY = 0x07,
    VGA_COLOR_DARK_GREY = 0x08,
    VGA_COLOR_LIGHT_BLUE = 0x09,
    VGA_COLOR_LIGHT_GREEN = 0x0A,
    VGA_COLOR_LIGHT_CYAN = 0x0B,
    VGA_COLOR_LIGHT_RED = 0x0C,
    VGA_COLOR_LIGHT_MAGENTA = 0x0D,
    VGA_COLOR_YELLOW = 0x0E,
    VGA_COLOR_WHITE = 0x0F,
} vga_color_t;

#endif  // VGA_COLORS_H